name: containers

on:
  push:
    branches:
      - master
      - int/**

jobs:
  build-dev:
    name: build dev container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Docker compose build
      run: docker-compose build dev_container

