name: hugo

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy'
        required: false 
        type: boolean
  push:
    branches:
      - master
      - int/**

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build
      run: ./tools/prod/build.sh

    - name: Deploy
      if: ${{ github.ref == 'refs/heads/master' || github.event.inputs.deploy }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        ./tools/prod/deploy.sh

